#Dockerfile to generate base image on top of ArchLinux with OpenJDK
FROM pcompton/archlinux
MAINTAINER Phil Compton <me@philcompton.com>
ENV BUILD_DATE 2015.08.26

RUN pacman -S jdk8-openjdk --noconfirm
