#Dockerfile to generate base Ubuntu Vivid Vervet
FROM ubuntu:vivid
MAINTAINER Phil Compton <me@philcompton.com>
ENV BUILD_DATE 2015.07.22
RUN apt-get update && apt-get -y upgrade && apt-get clean

CMD /bin/bash
