#Dockerfile to generate base jre image on Fedora
FROM pcompton/fedora:22
MAINTAINER Phil Compton <me@philcompton.com>
ENV BUILD_DATE 2015.09.06

RUN dnf install -y java-1.8.0-openjdk-headless.x86_64

